### ISSUE TITLE
Search link that point to the same page have no effect

### ISSUE THREAD

**Issue by ndufresne** [hotdoc/hotdoc_search_extension#2]
Let's say I serach GstBin, I open the page, and then I search GstBin again. Clicking on the link does not go back to the GstBin page.

**Comment by MathieuDuponchelle** [comment]
That is indeed very much a bug, thanks for reporting that I'll fix it as soon as I can :)

**Comment by MathieuDuponchelle** [comment]
Fixed, thanks for the report :)
