### ISSUE TITLE
namespace grab: installs a top-level Python package named "javascript"

### ISSUE THREAD

**Issue by smcv** [hotdoc/hotdoc_search_extension#3]
An installed copy of this extension contains:

```
./usr/lib/python2.7/dist-packages/javascript/
./usr/lib/python2.7/dist-packages/javascript/__init__.py
./usr/lib/python2.7/dist-packages/javascript/trie.js
./usr/lib/python2.7/dist-packages/javascript/search.js
```

These would break a Python package named `javascript` (as in `import javascript`), if someone wrote one. It would also break any other package that does the same thing you did.

The JS should either be in a subdirectory of `hotdoc_search_extension`, or under `/usr/share` somewhere.

**Comment by MathieuDuponchelle** [comment]
Fixed
